name: Cherry-pick to develop

on:
  push:
    branches:
      # - 'v[0-9]+.[0-9]+' # Matches branches like v1.23, v10.45, etc.
      - 'testing'

jobs:
  cherry_pick:
    runs-on: self-hosted

    steps:
    # Checkout the repository with full history
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Configure Git
    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    # Cherry-pick the commit
    - name: Cherry-pick commit to develop
      run: |
        # git checkout develop
        git fetch origin master
        git checkout master
        git reset --hard origin/master
        echo "Head Commit ID: ${{ github.event.head_commit.id }}"
        git cherry-pick ${{ github.event.head_commit.id }}
        # git push origin develop
        git branch
        git status
        git push origin master

    # Handle Cherry-pick Conflicts
    - name: Handle cherry-pick conflicts
      if: failure()
      run: |
        echo "Cherry-pick failed due to conflicts. Aborting..."
        git cherry-pick --abort
        exit 1
